server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.24.192.174:3306/movie_rec
    username: root
    password: useradmin@YNU
  data:
    redis:
      host: localhost
      port: 6379

#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
